const Gallery = {
	"Gestures": {
		"Day 1.png":{"path": "Gallery/Gestures/Day 1.png"},
		"Day 2.png":{"path": "Gallery/Gestures/Day 2.png"},
		"Day 3.png":{"path": "Gallery/Gestures/Day 3.png"},
		"Day 4.png":{"path": "Gallery/Gestures/Day 4.png"},
		"Day 5.png":{"path": "Gallery/Gestures/Day 5.png"},
		"Day 6.png":{"path": "Gallery/Gestures/Day 6.png"},
		"Day 7.png":{"path": "Gallery/Gestures/Day 7.png"},
		"Day 8.png":{"path": "Gallery/Gestures/Day 8.png"},
		"Day 9.png":{"path": "Gallery/Gestures/Day 9.png"},
		"Day 10.png":{"path": "Gallery/Gestures/Day 10.png"},
		"Day 11.png":{"path": "Gallery/Gestures/Day 11.png"},
		"Day 12.png":{"path": "Gallery/Gestures/Day 12.png"},
		"Day 13.png":{"path": "Gallery/Gestures/Day 13.png"},
		"Day 14.png":{"path": "Gallery/Gestures/Day 14.png"},
		"Day 15.png":{"path": "Gallery/Gestures/Day 15.png"},
		"Day 16 (Bad Day).png":{"path": "Gallery/Gestures/Day 16 (Bad Day).png"},
		"Day 17.png":{"path": "Gallery/Gestures/Day 17.png"},
		"Day 18.png":{"path": "Gallery/Gestures/Day 18.png"},
		"Day 19.png":{"path": "Gallery/Gestures/Day 19.png"},
		"Day 20.png":{"path": "Gallery/Gestures/Day 20.png"},
		"Day 21.png":{"path": "Gallery/Gestures/Day 21.png"},
		"Day 22.png":{"path": "Gallery/Gestures/Day 22.png"},
		"Day 23.png":{"path": "Gallery/Gestures/Day 23.png"},
		"Day 24.png":{"path": "Gallery/Gestures/Day 24.png"},
		"Day 25.png":{"path": "Gallery/Gestures/Day 25.png"},
		"Day 26.png":{"path": "Gallery/Gestures/Day 26.png"},
		"Day 27.png":{"path": "Gallery/Gestures/Day 27.png"},
		"Day 28.png":{"path": "Gallery/Gestures/Day 28.png"},
		"Day 29.png":{"path": "Gallery/Gestures/Day 29.png"},
		"Day 30.png":{"path": "Gallery/Gestures/Day 30.png"},
		"Day 31.png":{"path": "Gallery/Gestures/Day 31.png"},
		"Day 32.png":{"path": "Gallery/Gestures/Day 32.png"},
		"Day 33.png":{"path": "Gallery/Gestures/Day 33.png"},
		"Day 34.png":{"path": "Gallery/Gestures/Day 34.png"},
		"Day 35.png":{"path": "Gallery/Gestures/Day 35.png"},
		"Day 36.png":{"path": "Gallery/Gestures/Day 36.png"},
		"Day 37.png":{"path": "Gallery/Gestures/Day 37.png"},
		"Day 38.png":{"path": "Gallery/Gestures/Day 38.png"},
		"Day 39.png":{"path": "Gallery/Gestures/Day 39.png"},
		"Day 40.png":{"path": "Gallery/Gestures/Day 40.png"},
		"Day 41.png":{"path": "Gallery/Gestures/Day 41.png"},
		"Day 42.png":{"path": "Gallery/Gestures/Day 42.png"},
		"Day 43.png":{"path": "Gallery/Gestures/Day 43.png"},
		"Day 44.png":{"path": "Gallery/Gestures/Day 44.png"},
		"Day 45.png":{"path": "Gallery/Gestures/Day 45.png"},
		"Day 46.png":{"path": "Gallery/Gestures/Day 46.png"},
		"Day 47.png":{"path": "Gallery/Gestures/Day 47.png"},
		"Day 48.png":{"path": "Gallery/Gestures/Day 48.png"},
		"Day 49.png":{"path": "Gallery/Gestures/Day 49.png"},
		"Day 50.png":{"path": "Gallery/Gestures/Day 50.png"},
		"Day 51.png":{"path": "Gallery/Gestures/Day 51.png"},
		"Day 52.png":{"path": "Gallery/Gestures/Day 52.png"},
		"Day 53.png":{"path": "Gallery/Gestures/Day 53.png"},
		"Day 54.png":{"path": "Gallery/Gestures/Day 54.png"},
		"Day 55.png":{"path": "Gallery/Gestures/Day 55.png"},
		"Day 56.png":{"path": "Gallery/Gestures/Day 56.png"},
		"Day 57.png":{"path": "Gallery/Gestures/Day 57.png"},
		"Day 58.png":{"path": "Gallery/Gestures/Day 58.png"},
		"Day 59.png":{"path": "Gallery/Gestures/Day 59.png"},
		"Day 60.png":{"path": "Gallery/Gestures/Day 60.png"},
		"Day 61.png":{"path": "Gallery/Gestures/Day 61.png"},
		"Day 62.png":{"path": "Gallery/Gestures/Day 62.png"},
		"Day 63.png":{"path": "Gallery/Gestures/Day 63.png"},
		"Day 64.png":{"path": "Gallery/Gestures/Day 64.png"},
		"Day 65.png":{"path": "Gallery/Gestures/Day 65.png"},
		"Day 66.png":{"path": "Gallery/Gestures/Day 66.png"},
		"Day 67.png":{"path": "Gallery/Gestures/Day 67.png"},
		"Day 68.png":{"path": "Gallery/Gestures/Day 68.png"},
		"Day 69.png":{"path": "Gallery/Gestures/Day 69.png"},
		"Day 70.png":{"path": "Gallery/Gestures/Day 70.png"},
		"Day 71.png":{"path": "Gallery/Gestures/Day 71.png"},
		"Day 72.png":{"path": "Gallery/Gestures/Day 72.png"},
		"Day 73.png":{"path": "Gallery/Gestures/Day 73.png"},
		"Day 74.png":{"path": "Gallery/Gestures/Day 74.png"},
		"Day 75.png":{"path": "Gallery/Gestures/Day 75.png"},
		"Day 76.png":{"path": "Gallery/Gestures/Day 76.png"},
		"Day 77.png":{"path": "Gallery/Gestures/Day 77.png"},
		"Day 78.png":{"path": "Gallery/Gestures/Day 78.png"},
		"Day 79.png":{"path": "Gallery/Gestures/Day 79.png"},
		"Day 80 (sick).png":{"path": "Gallery/Gestures/Day 80 (sick).png"},
		"Day 81.png":{"path": "Gallery/Gestures/Day 81.png"},
		"Day 82.png":{"path": "Gallery/Gestures/Day 82.png"},
		"Day 83.png":{"path": "Gallery/Gestures/Day 83.png"},
		"Day 84.png":{"path": "Gallery/Gestures/Day 84.png"},
		"Day 85 (tired).png":{"path": "Gallery/Gestures/Day 85 (tired).png"},
		"Day 86.png":{"path": "Gallery/Gestures/Day 86.png"},
		"Day 87.png":{"path": "Gallery/Gestures/Day 87.png"},
		"Day 88.png":{"path": "Gallery/Gestures/Day 88.png"},
		"Day 89.png":{"path": "Gallery/Gestures/Day 89.png"},
		"Day 90.png":{"path": "Gallery/Gestures/Day 90.png"},
		"Day 91 (sick).png":{"path": "Gallery/Gestures/Day 91 (sick).png"},
		"Day 92.png":{"path": "Gallery/Gestures/Day 92.png"},
		"Day 93.png":{"path": "Gallery/Gestures/Day 93.png"},
		"Day 94.png":{"path": "Gallery/Gestures/Day 94.png"},
		"Day 95.png":{"path": "Gallery/Gestures/Day 95.png"},
		"Day 96 (free).png":{"path": "Gallery/Gestures/Day 96 (free).png"},
		"Day 97.png":{"path": "Gallery/Gestures/Day 97.png"},
		"Day 97 (Sketch).png":{"path": "Gallery/Gestures/Day 97 (Sketch).png"}
	},
	"Anatomy": {
		"Faces": {
			"Throwaways": {
				"Throwaway(1).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(1).png"},
				"Throwaway(2).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(2).png"},
				"Throwaway(3).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(3).png"},
				"Throwaway(4).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(4).png"},
				"Throwaway(5).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(5).png"},
				"Throwaway(6).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(6).png"},
				"Throwaway(7).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(7).png"},
				"Throwaway(8).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(8).png"},
				"Throwaway(8.5).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(8.5).png"},
				"Throwaway(9).png":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(9).png"},
				"Throwaway(10).webp":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(10).webp"},
				"Throwaway(11).webp":{"path": "Gallery/Anatomy/Faces/Throwaways/Throwaway(11).webp"}
			},
			"Power Girl": {
				"powergirl wip.png":{"path": "Gallery/Anatomy/Faces/Power Girl/powergirl wip.png"},
				"powergirl1.png":{"path": "Gallery/Anatomy/Faces/Power Girl/powergirl1.png"},
				"powergirl1 detailed.png":{"path": "Gallery/Anatomy/Faces/Power Girl/powergirl1 detailed.png"},
				"powergirl wip2.png":{"path": "Gallery/Anatomy/Faces/Power Girl/powergirl wip2.png"}
			},
			"Sheena.webp":{"path": "Gallery/Anatomy/Faces/Sheena.webp"},
			"Failed Ringo.png":{"path": "Gallery/Anatomy/Faces/Failed Ringo.png"}
		},
		"Notes": {
			"Pelvis Notes 7-6-2025.png":{"path": "Gallery/Anatomy/Notes/Pelvis Notes 7-6-2025.png"},
			"Pelvis Notes 7-8-2025.png":{"path": "Gallery/Anatomy/Notes/Pelvis Notes 7-8-2025.png"},
			"Pelvis Notes 7-9-2025.png":{"path": "Gallery/Anatomy/Notes/Pelvis Notes 7-9-2025.png"},
			"Proportions.png":{"path": "Gallery/Anatomy/Notes/Proportions.png"},
			"Proportions (deprecated).png":{"path": "Gallery/Anatomy/Notes/Proportions (deprecated).png"}
		},
		"Throwaways": {
			"Throwaway (1).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (1).png"},
			"Throwaway (2).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (2).png"},
			"Throwaway (3).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (3).png"},
			"Throwaway (4).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (4).png"},
			"Throwaway (5).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (5).png"},
			"Throwaway (6).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (6).png"},
			"Throwaway (7).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (7).png"},
			"Throwaway (8).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (8).png"},
			"Throwaway (9).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (9).png"},
			"Throwaway (10).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (10).png"},
			"Throwaway (11).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (11).png"},
			"Throwaway (12).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (12).png"},
			"Throwaway (13).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (13).png"},
			"Throwaway (14).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway (14).png"},
			"Throwaway(15).webp":{"path": "Gallery/Anatomy/Throwaways/Throwaway(15).webp"},
			"Throwaway(16).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(16).png"},
			"Throwaway(17).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(17).png"},
			"Throwaway(18).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(18).png"},
			"Throwaway(19).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(19).png"},
			"Throwaway(20).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(20).png"},
			"Throwaway(21).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(21).png"},
			"Throwaway(22).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(22).png"},
			"Throwaway(23).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(23).png"},
			"Throwaway(24).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(24).png"},
			"Throwaway(25).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(25).png"},
			"Throwaway(26).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(26).png"},
			"Throwaway(27).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(27).png"},
			"Throwaway(28).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(28).png"},
			"Throwaway(29).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(29).png"},
			"Throwaway(30).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(30).png"},
			"Throwaway(31).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(31).png"},
			"Throwaway(32).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(32).png"},
			"Throwaway(33).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(33).png"},
			"Throwaway(34).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(34).png"},
			"Throwaway(35).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(35).png"},
			"Throwaway(36).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(36).png"},
			"Throwaway(37).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(37).png"},
			"Throwaway(38).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(38).png"},
			"Throwaway(39).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(39).png"},
			"Throwaway(40).png":{"path": "Gallery/Anatomy/Throwaways/Throwaway(40).png"},
			"Ass!.png":{"path": "Gallery/Anatomy/Throwaways/Ass!.png"},
			"fullbody.png":{"path": "Gallery/Anatomy/Throwaways/fullbody.png"},
			"Glute.png":{"path": "Gallery/Anatomy/Throwaways/Glute.png"}
		}
	},
	"Shapes": {
		"cylinder drill.png":{"path": "Gallery/Shapes/cylinder drill.png"},
		"detailed cylinder drill.png":{"path": "Gallery/Shapes/detailed cylinder drill.png"},
		"Shape Practice 2.png":{"path": "Gallery/Shapes/Shape Practice 2.png"},
		"PerspectiveCubes.png":{"path": "Gallery/Shapes/PerspectiveCubes.png"}
	},
	"Landscapes": {
		"fini.png":{"path": "Gallery/Landscapes/fini.png"},
		"pixelized.png":{"path": "Gallery/Landscapes/pixelized.png"}
	},
	"Completed": {
		"Hornet": {
			"Day1.png":{"path": "Gallery/Completed/Hornet/Day1.png"},
			"Day2.png":{"path": "Gallery/Completed/Hornet/Day2.png"},
			"CompleteLinework.png":{"path": "Gallery/Completed/Hornet/CompleteLinework.png"},
			"Day4.png":{"path": "Gallery/Completed/Hornet/Day4.png"},
			"Shading.png":{"path": "Gallery/Completed/Hornet/Shading.png"},
			"complete.png":{"path": "Gallery/Completed/Hornet/complete.png"}
		},
		"Comic": {
			"wip.png":{"path": "Gallery/Completed/Comic/wip.png"},
			"wip2.png":{"path": "Gallery/Completed/Comic/wip2.png"},
			"comic.png":{"path": "Gallery/Completed/Comic/comic.png"}
		}
	}
};
const metaData = [
	"Gallery/Gestures/Day 1.png",
	"Gallery/Gestures/Day 2.png",
	"Gallery/Gestures/Day 3.png",
	"Gallery/Gestures/Day 4.png",
	"Gallery/Gestures/Day 5.png",
	"Gallery/Gestures/Day 6.png",
	"Gallery/Gestures/Day 7.png",
	"Gallery/Gestures/Day 8.png",
	"Gallery/Gestures/Day 9.png",
	"Gallery/Gestures/Day 10.png",
	"Gallery/Gestures/Day 11.png",
	"Gallery/Gestures/Day 12.png",
	"Gallery/Gestures/Day 13.png",
	"Gallery/Gestures/Day 14.png",
	"Gallery/Gestures/Day 15.png",
	"Gallery/Gestures/Day 16 (Bad Day).png",
	"Gallery/Gestures/Day 17.png",
	"Gallery/Gestures/Day 18.png",
	"Gallery/Gestures/Day 19.png",
	"Gallery/Gestures/Day 20.png",
	"Gallery/Gestures/Day 21.png",
	"Gallery/Gestures/Day 22.png",
	"Gallery/Gestures/Day 23.png",
	"Gallery/Gestures/Day 24.png",
	"Gallery/Gestures/Day 25.png",
	"Gallery/Gestures/Day 26.png",
	"Gallery/Gestures/Day 27.png",
	"Gallery/Gestures/Day 28.png",
	"Gallery/Gestures/Day 29.png",
	"Gallery/Gestures/Day 30.png",
	"Gallery/Gestures/Day 31.png",
	"Gallery/Gestures/Day 32.png",
	"Gallery/Gestures/Day 33.png",
	"Gallery/Gestures/Day 34.png",
	"Gallery/Gestures/Day 35.png",
	"Gallery/Gestures/Day 36.png",
	"Gallery/Gestures/Day 37.png",
	"Gallery/Gestures/Day 38.png",
	"Gallery/Gestures/Day 39.png",
	"Gallery/Gestures/Day 40.png",
	"Gallery/Gestures/Day 41.png",
	"Gallery/Gestures/Day 42.png",
	"Gallery/Gestures/Day 43.png",
	"Gallery/Gestures/Day 44.png",
	"Gallery/Gestures/Day 45.png",
	"Gallery/Gestures/Day 46.png",
	"Gallery/Gestures/Day 47.png",
	"Gallery/Gestures/Day 48.png",
	"Gallery/Gestures/Day 49.png",
	"Gallery/Gestures/Day 50.png",
	"Gallery/Gestures/Day 51.png",
	"Gallery/Gestures/Day 52.png",
	"Gallery/Gestures/Day 53.png",
	"Gallery/Gestures/Day 54.png",
	"Gallery/Gestures/Day 55.png",
	"Gallery/Gestures/Day 56.png",
	"Gallery/Gestures/Day 57.png",
	"Gallery/Gestures/Day 58.png",
	"Gallery/Gestures/Day 59.png",
	"Gallery/Gestures/Day 60.png",
	"Gallery/Gestures/Day 61.png",
	"Gallery/Gestures/Day 62.png",
	"Gallery/Gestures/Day 63.png",
	"Gallery/Gestures/Day 64.png",
	"Gallery/Gestures/Day 65.png",
	"Gallery/Gestures/Day 66.png",
	"Gallery/Gestures/Day 67.png",
	"Gallery/Gestures/Day 68.png",
	"Gallery/Gestures/Day 69.png",
	"Gallery/Gestures/Day 70.png",
	"Gallery/Gestures/Day 71.png",
	"Gallery/Gestures/Day 72.png",
	"Gallery/Gestures/Day 73.png",
	"Gallery/Gestures/Day 74.png",
	"Gallery/Gestures/Day 75.png",
	"Gallery/Gestures/Day 76.png",
	"Gallery/Gestures/Day 77.png",
	"Gallery/Gestures/Day 78.png",
	"Gallery/Gestures/Day 79.png",
	"Gallery/Gestures/Day 80 (sick).png",
	"Gallery/Gestures/Day 81.png",
	"Gallery/Gestures/Day 82.png",
	"Gallery/Gestures/Day 83.png",
	"Gallery/Gestures/Day 84.png",
	"Gallery/Gestures/Day 85 (tired).png",
	"Gallery/Gestures/Day 86.png",
	"Gallery/Gestures/Day 87.png",
	"Gallery/Gestures/Day 88.png",
	"Gallery/Gestures/Day 89.png",
	"Gallery/Gestures/Day 90.png",
	"Gallery/Gestures/Day 91 (sick).png",
	"Gallery/Gestures/Day 92.png",
	"Gallery/Gestures/Day 93.png",
	"Gallery/Gestures/Day 94.png",
	"Gallery/Gestures/Day 95.png",
	"Gallery/Gestures/Day 96 (free).png",
	"Gallery/Gestures/Day 97.png",
	"Gallery/Gestures/Day 97 (Sketch).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(1).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(2).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(3).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(4).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(5).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(6).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(7).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(8).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(8.5).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(9).png",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(10).webp",
	"Gallery/Anatomy/Faces/Throwaways/Throwaway(11).webp",
	"Gallery/Anatomy/Faces/Power Girl/powergirl wip.png",
	"Gallery/Anatomy/Faces/Power Girl/powergirl1.png",
	"Gallery/Anatomy/Faces/Power Girl/powergirl1 detailed.png",
	"Gallery/Anatomy/Faces/Power Girl/powergirl wip2.png",
	"Gallery/Anatomy/Faces/Sheena.webp",
	"Gallery/Anatomy/Faces/Failed Ringo.png",
	"Gallery/Anatomy/Notes/Pelvis Notes 7-6-2025.png",
	"Gallery/Anatomy/Notes/Pelvis Notes 7-8-2025.png",
	"Gallery/Anatomy/Notes/Pelvis Notes 7-9-2025.png",
	"Gallery/Anatomy/Notes/Proportions.png",
	"Gallery/Anatomy/Notes/Proportions (deprecated).png",
	"Gallery/Anatomy/Throwaways/Throwaway (1).png",
	"Gallery/Anatomy/Throwaways/Throwaway (2).png",
	"Gallery/Anatomy/Throwaways/Throwaway (3).png",
	"Gallery/Anatomy/Throwaways/Throwaway (4).png",
	"Gallery/Anatomy/Throwaways/Throwaway (5).png",
	"Gallery/Anatomy/Throwaways/Throwaway (6).png",
	"Gallery/Anatomy/Throwaways/Throwaway (7).png",
	"Gallery/Anatomy/Throwaways/Throwaway (8).png",
	"Gallery/Anatomy/Throwaways/Throwaway (9).png",
	"Gallery/Anatomy/Throwaways/Throwaway (10).png",
	"Gallery/Anatomy/Throwaways/Throwaway (11).png",
	"Gallery/Anatomy/Throwaways/Throwaway (12).png",
	"Gallery/Anatomy/Throwaways/Throwaway (13).png",
	"Gallery/Anatomy/Throwaways/Throwaway (14).png",
	"Gallery/Anatomy/Throwaways/Throwaway(15).webp",
	"Gallery/Anatomy/Throwaways/Throwaway(16).png",
	"Gallery/Anatomy/Throwaways/Throwaway(17).png",
	"Gallery/Anatomy/Throwaways/Throwaway(18).png",
	"Gallery/Anatomy/Throwaways/Throwaway(19).png",
	"Gallery/Anatomy/Throwaways/Throwaway(20).png",
	"Gallery/Anatomy/Throwaways/Throwaway(21).png",
	"Gallery/Anatomy/Throwaways/Throwaway(22).png",
	"Gallery/Anatomy/Throwaways/Throwaway(23).png",
	"Gallery/Anatomy/Throwaways/Throwaway(24).png",
	"Gallery/Anatomy/Throwaways/Throwaway(25).png",
	"Gallery/Anatomy/Throwaways/Throwaway(26).png",
	"Gallery/Anatomy/Throwaways/Throwaway(27).png",
	"Gallery/Anatomy/Throwaways/Throwaway(28).png",
	"Gallery/Anatomy/Throwaways/Throwaway(29).png",
	"Gallery/Anatomy/Throwaways/Throwaway(30).png",
	"Gallery/Anatomy/Throwaways/Throwaway(31).png",
	"Gallery/Anatomy/Throwaways/Throwaway(32).png",
	"Gallery/Anatomy/Throwaways/Throwaway(33).png",
	"Gallery/Anatomy/Throwaways/Throwaway(34).png",
	"Gallery/Anatomy/Throwaways/Throwaway(35).png",
	"Gallery/Anatomy/Throwaways/Throwaway(36).png",
	"Gallery/Anatomy/Throwaways/Throwaway(37).png",
	"Gallery/Anatomy/Throwaways/Throwaway(38).png",
	"Gallery/Anatomy/Throwaways/Throwaway(39).png",
	"Gallery/Anatomy/Throwaways/Throwaway(40).png",
	"Gallery/Anatomy/Throwaways/Ass!.png",
	"Gallery/Anatomy/Throwaways/fullbody.png",
	"Gallery/Anatomy/Throwaways/Glute.png",
	"Gallery/Shapes/cylinder drill.png",
	"Gallery/Shapes/detailed cylinder drill.png",
	"Gallery/Shapes/Shape Practice 2.png",
	"Gallery/Shapes/PerspectiveCubes.png",
	"Gallery/Landscapes/fini.png",
	"Gallery/Landscapes/pixelized.png",
	"Gallery/Completed/Hornet/Day1.png",
	"Gallery/Completed/Hornet/Day2.png",
	"Gallery/Completed/Hornet/CompleteLinework.png",
	"Gallery/Completed/Hornet/Day4.png",
	"Gallery/Completed/Hornet/Shading.png",
	"Gallery/Completed/Hornet/complete.png",
	"Gallery/Completed/Comic/wip.png",
	"Gallery/Completed/Comic/wip2.png",
	"Gallery/Completed/Comic/comic.png",
];

